language: python
python:
  - "2.7"
  - "3.2"
env:
  - DJANGO_VERSION=1.6.1
  - DJANGO_VERSION=1.7a1
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - pybot test.robot
