language: python
python:
  - 2.7
  - 3.5
dist: trusty
sudo: false
env:
  - DJANGO_VERSION=1.8.12 DB=SQLite
  - DJANGO_VERSION=1.9.5 DB=SQLite
  - DJANGO_VERSION=1.10.7 DB=SQLite
  - DJANGO_VERSION=1.11.1 DB=SQLite
  - DJANGO_VERSION=1.8.12 DB=Postgres
  - DJANGO_VERSION=1.9.5 DB=Postgres
  - DJANGO_VERSION=1.10.7 DB=Postgres
  - DJANGO_VERSION=1.11.1 DB=Postgres
services:
  – postgresql
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  # for Python 3 we need robotframework-selenium2library 1.8.x
  - if [ $TRAVIS_PYTHON_VERSION == 3.5 ]; then pip install -U https://github.com/HelioGuilherme66/robotframework-selenium2library/archive/v1.8.0b3.tar.gz; fi
  - pip install -r requirements.txt
  - pip install . --no-dependencies
  - pip install -q flake8
  - pip install -q psycopg2
  - pip install -q  --pre Django==$DJANGO_VERSION
#  - python setup.py install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database robotframework;' -U postgres
  # - django-admin startproject mysite
script:
  - flake8 DjangoLibrary
  - py.test mysite
  - pybot DjangoLibrary/tests/
after_script:
  - firefox --version
